[package]
name = "hello_exercism"
version = "0.1.2"
authors = ["cnruby <gudao.luo@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
repository = "https://github.com/cnruby/exercism.io/tree/master/hello-world"
description = """

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
