[book]
authors = ["Gudao Luo"]
language = "en"
multilingual = false
src = "src"
title = "Learn Rust by Crates"
description = "English"

[build]
build-dir = "../volumn-one"

[output.html]
mathjax-support = true

[output.html.playpen]
editable = true

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2
